services:
  - type: web
    name: agromind-backend
    env: python
    plan: free
    rootDir: FintechAgri/backend
    buildCommand: pip install -r requirements.txt
    startCommand: python seed_db.py && uvicorn main:app --host 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ALGORITHM
        value: HS256
